name: Upload file to Azure VM
on:
  push:
    branches:
      - main
jobs:
  upload-file:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Azure PowerShell module
        run: Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
      - name: Run PowerShell script
        shell: pwsh
        env:
          AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
          AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          .\upload-file-to-vm.ps1
